version: "3.8"

services:
  app:
    container_name: antigenapp_app
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/antigenapp/src:ro
      - ./frontend/tests:/antigenapp/tests:ro
      - ./frontend/public:/antigenapp/public:ro
  api:
    container_name: antigenapp_api
    build:
      context: backend
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - ./backend:/usr/src
      - api_data:/api_data
      - ./db.sqlite3:/usr/src/db.sqlite3
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "localhost"
      DJANGO_USE_SQLITE: "true"
      UWSGI_THREADS: 2
      UWSGI_PROCESSES: 1
      UWSGI_OFFLOAD_THREADS: 2
      UWSGI_MODULE: antigendjango.wsgi:application
      DJANGO_SECRET_KEY: __insecure__ahTiicei4Quauk7d__
  ws:
    container_name: antigenapp_ws
    image: registry.hub.docker.com/library/nginx:stable
    restart: always
    command: nginx -g "daemon off;"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:z
      - ./api_nginx.conf:/etc/nginx/sites-available/api_nginx.conf:z
      - api_data:/api_data
    ports:
      - 8000:80

volumes:
  api_data:
