version: "3.8"

services:
  app:
    container_name: antigenapp_app
    build: frontend/
    restart: always
    ports:
      - 3000:3000
    volumes:
     - ./frontend/src:/antigenapp/src:ro
     - ./frontend/public:/antigenapp/public:ro
  api:
    container_name: antigenapp_api
    build: backend/
    restart: always
    volumes:
      - ./backend:/antigenapp
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "localhost"
      DJANGO_USE_SQLITE: "true"
      UWSGI_THREADS: 2
      UWSGI_PROCESSES: 1
      UWSGI_OFFLOAD_THREADS: 2
      UWSGI_MODULE: antigendjango.wsgi:application
      DJANGO_SECRET_KEY: __insecure__ahTiicei4Quauk7d__
  ws:
    container_name: antigenapp_ws
    image: registry.hub.docker.com/library/nginx:stable
    restart: always
    command: nginx -g "daemon off;"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:z
      - ./api_nginx.conf:/etc/nginx/sites-available/api_nginx.conf:z
    ports:
      - 8000:80

volumes:
  api_data:
