# Generated by Django 4.1.2 on 2023-01-26 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(max_length=16, null=True, unique=True)),
                ('preferred_name', models.CharField(max_length=256)),
                ('sequence', models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[ARNDCHIQEGLKMFPSTWYVBZX]*$')])),
                ('molecular_mass', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('epitope', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElisaPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optical_density_threshold', models.FloatField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('short_title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Llama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_num', models.CharField(max_length=32)),
                ('immunisation_date', models.DateField(null=True)),
                ('blood_draw_date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('llama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='antigenapi.llama')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='antigenapi.project')),
            ],
        ),
        migrations.CreateModel(
            name='ElisaWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.PositiveSmallIntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'A6'), (7, 'A7'), (8, 'A8'), (9, 'A9'), (10, 'A10'), (11, 'A11'), (12, 'A12'), (13, 'B1'), (14, 'B2'), (15, 'B3'), (16, 'B4'), (17, 'B5'), (18, 'B6'), (19, 'B7'), (20, 'B8'), (21, 'B9'), (22, 'B10'), (23, 'B11'), (24, 'B12'), (25, 'C1'), (26, 'C2'), (27, 'C3'), (28, 'C4'), (29, 'C5'), (30, 'C6'), (31, 'C7'), (32, 'C8'), (33, 'C9'), (34, 'C10'), (35, 'C11'), (36, 'C12'), (37, 'D1'), (38, 'D2'), (39, 'D3'), (40, 'D4'), (41, 'D5'), (42, 'D6'), (43, 'D7'), (44, 'D8'), (45, 'D9'), (46, 'D10'), (47, 'D11'), (48, 'D12'), (49, 'E1'), (50, 'E2'), (51, 'E3'), (52, 'E4'), (53, 'E5'), (54, 'E6'), (55, 'E7'), (56, 'E8'), (57, 'E9'), (58, 'E10'), (59, 'E11'), (60, 'E12'), (61, 'F1'), (62, 'F2'), (63, 'F3'), (64, 'F4'), (65, 'F5'), (66, 'F6'), (67, 'F7'), (68, 'F8'), (69, 'F9'), (70, 'F10'), (71, 'F11'), (72, 'F12'), (73, 'G1'), (74, 'G2'), (75, 'G3'), (76, 'G4'), (77, 'G5'), (78, 'G6'), (79, 'G7'), (80, 'G8'), (81, 'G9'), (82, 'G10'), (83, 'G11'), (84, 'G12'), (85, 'H1'), (86, 'H2'), (87, 'H3'), (88, 'H4'), (89, 'H5'), (90, 'H6'), (91, 'H7'), (92, 'H8'), (93, 'H9'), (94, 'H10'), (95, 'H11'), (96, 'H12')])),
                ('optical_density', models.FloatField(null=True)),
                ('antigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='antigenapi.antigen')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antigenapi.elisaplate')),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.AddConstraint(
            model_name='elisawell',
            constraint=models.UniqueConstraint(fields=('plate', 'location'), name='unique_well'),
        ),
    ]
