# Generated by Django 4.1.7 on 2023-06-25 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("antigenapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequencingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_thresholds", models.JSONField()),
                ("wells", models.JSONField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("sent_date", models.DateField(null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="elisaplate",
            name="optical_density_threshold",
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                fields=("project", "cohort"), name="unique_project_cohort"
            ),
        ),
        migrations.AddField(
            model_name="sequencingrun",
            name="added_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
