# Generated by Django 4.1.7 on 2023-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0002_sequencing_runs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sequencingrunwell",
            name="elisa_well",
        ),
        migrations.RemoveField(
            model_name="sequencingrunwell",
            name="sequencing_run",
        ),
        migrations.RemoveField(
            model_name="sequencingrun",
            name="results_date",
        ),
        migrations.RemoveField(
            model_name="sequencingrun",
            name="results_file",
        ),
        migrations.AddField(
            model_name="sequencingrun",
            name="plate_thresholds",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sequencingrun",
            name="wells",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SequencingRunPlateThreshold",
        ),
        migrations.DeleteModel(
            name="SequencingRunWell",
        ),
    ]
