# Generated by Django 4.2.5 on 2023-10-03 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("antigenapi", "0004_remove_sequencingrun_results_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequencingRunResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveSmallIntegerField()),
                (
                    "seqres_file",
                    models.FileField(upload_to="uploads/sequencingresults/"),
                ),
                (
                    "parameters_file",
                    models.FileField(upload_to="uploads/sequencingresults/"),
                ),
                ("airr_file", models.FileField(upload_to="uploads/sequencingresults/")),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequencing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="antigenapi.sequencingrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sequencingrunresults",
            constraint=models.UniqueConstraint(
                fields=("sequencing_run", "seq"), name="unique_seqrun_seq"
            ),
        ),
    ]
