# Generated by Django 4.1.7 on 2023-09-14 10:19

import random
import string

from django.db import migrations, models
from django.db.models import F


def copy_uniprot_id_to_short_name(apps, schema_editor):
    """Copy UniProt ID to short_name field during migration."""
    MetaDataValue = apps.get_model("antigenapi", "antigen")
    db_alias = schema_editor.connection.alias
    MetaDataValue.objects.using(db_alias).all().update(short_name=F("uniprot_id"))


def generate_random_value():
    """Generate random placeholder string."""
    characters = string.ascii_letters + string.digits
    return f"changeme_{''.join(random.choice(characters) for _ in range(16))}"


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0004_remove_sequencingrun_results_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antigen",
            name="short_name",
            field=models.CharField(
                default=generate_random_value, max_length=32, null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(copy_uniprot_id_to_short_name),
    ]
