# Generated by Django 4.2.6 on 2024-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0007_sequencingrunresults_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequencingrunresults",
            name="well_pos_offset",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
