# Generated by Django 4.2.6 on 2024-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0008_seq_run_well_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="is_naive",
            field=models.BooleanField(default=False),
        ),
    ]
