# Generated by Django 4.2.6 on 2024-07-07 19:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("antigenapi", "0009_naive_cohorts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nanobody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "cdr3",
                    models.TextField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[ARNDCHIQEGLKMFPSTWYVBZX]*$"
                            )
                        ],
                    ),
                ),
                (
                    "seqruns",
                    models.ManyToManyField(
                        related_name="nanobodies", to="antigenapi.sequencingrunresults"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
