# Generated by Django 5.1.4 on 2025-03-09 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0012_rename_cdr3_nanobody_sequence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elisaplate",
            old_name="pan_round",
            new_name="comments",
        ),
        migrations.AddField(
            model_name="elisaplate",
            name="pan_round_concentration",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
