# Generated by Django 5.1.2 on 2025-04-09 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0014_antigen_short_long_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="library",
            name="unique_project_cohort",
        ),
        migrations.AddField(
            model_name="library",
            name="sublibrary",
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                fields=("project", "cohort", "sublibrary"), name="unique_project_cohort"
            ),
        ),
    ]
