# Generated by Django 5.1.2 on 2025-04-22 10:26

from django.db import migrations, models

import antigenapi.models


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0015_sublibraries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="sublibrary",
            field=models.TextField(
                max_length=32,
                null=True,
                validators=[antigenapi.models.validate_sublibrary_prefix],
            ),
        ),
    ]
