# Generated by Django 5.2.7 on 2026-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antigenapi", "0016_alter_library_sublibrary"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequencingrun",
            name="fill_horizontal",
            field=models.BooleanField(default=False),
        ),
    ]
