---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: antigenapp-prod
  namespace: antigenapp
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  instances:
    - name: pgha1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: ...
        resources:
          requests:
            storage: 10Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: antigenapp-prod
                    postgres-operator.crunchydata.com/instance-set: pgha1
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      configuration:
        - secret:
            name: antigen-prod-backrest-s3-config
      global:
        repo1-cipher-type: aes-256-cbc
        repo1-path: /pgbackrest/postgres-operator/antigen-prod/repo1
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          s3:
            bucket: ...
            endpoint: ...
            region: ...
          schedules:
            full: 16 3 * * *
