---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: antigen-prod-pdb
  namespace: antigenapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: antigen-prod-backend
