name: Backend Code CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # can add windows-latest, macos-latest
        python: ["3.11"]

    name: build/${{ matrix.python }}/${{ matrix.os }}/${{ matrix.pipenv }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python Dependencies
        run: |
          pip install pipenv build
          pipenv install --dev --python $(python -c 'import sys; print(sys.executable)') && pipenv graph

      - name: Run Tests
        run: DJANGO_CI=true pipenv run tests
