name: Container Images push to quay.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: rosalindfranklininstitute+github_antigenapp
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: backend
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/rosalindfranklininstitute/antigen-app-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: frontend
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/rosalindfranklininstitute/antigen-app-frontend:latest
