name: Frontend Code CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"] # can add windows-latest, macos-latest
        node-version: [12.x, 14.x, 16.x]

    name: build/${{ matrix.node-version }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        # require history to get back to last tag for version number of branches
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build --if-present
      
    - name: Unit Tests
      run: npm test
